defmodule FrontendChallengeWeb.Components.MenuManager do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  prop this_id, :integer
  slot default

  def render(assigns) do
    ~F"""
    <div>
      <#slot />
      <button :on-click={"del", target: "#tree"} value={@this_id}>
        delete
      </button>
      <div class="box">
        add
        <br>
        <button :on-click={"add_man", target: "#tree"} value={@this_id}>
          manager
        </button>
        <button :on-click={"add_dev", target: "#tree"} value={@this_id}>
          developer
        </button>
        <button :on-click={"add_qa", target: "#tree"} value={@this_id}>
          tester
        </button>
      </div>
    </div>
    """
  end
end
