defmodule FrontendChallengeWeb.Components.MenuManager do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  prop this_id, :integer
  slot default

  def render(assigns) do
    ~F"""
    <section class="teamborder">
      <div class="managerheader">
        <div>Manager-{@this_id}</div>
        <div> $300 </div>
        <button :on-click={"del", target: "#tree"} value={@this_id}>
          delete team
        </button>
      </div>
      <div class="box">
        <button :on-click={"add_man", target: "#tree"} value={@this_id}>
          +manager
        </button>
        <button :on-click={"add_dev", target: "#tree"} value={@this_id}>
          +developer
        </button>
        <button :on-click={"add_qa", target: "#tree"} value={@this_id}>
          +tester
        </button>
      </div>
      <#slot />
    </section>

    """
  end
end
